# Generated by Django 4.2.29 on 2026-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MockHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_id', models.CharField(max_length=50, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('concentration', models.FloatField()),
                ('anomaly_delta', models.FloatField()),
                ('emission_rate', models.FloatField()),
                ('plume_area', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('wind_direction_label', models.CharField(max_length=10)),
                ('nearest_facility', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('risk_level', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('detected_at', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('plume_length', models.FloatField()),
                ('plume_width', models.FloatField()),
            ],
        ),
    ]
